language: python
python:
  - "2.7"

before_install:
    - sudo apt-get update
    - sudo apt-get install libmysqlclient-dev
install:
    - travis_retry pip install tox==1.8
script:
    - tox -e py27
    - for f in `find . -name '*.json'` ./configs/watch_pending.cfg; do python -m json.tool $f; done
after_success:
    - tox -e py27-coveralls
