stacks:
  # TODO: figure out how to handle region naming suffixes
  RelengNetworkUsw1:
    region: us-west-1
    template: network.py
    options:
      region: usw1

  ITUsw1:
    region: us-west-1
    template: it.py
    options:
      vpcid:
        stack: RelengNetworkUsw1
        resource: RelengVPC

  TooltoolUsw1:
    region: us-west-1
    template: tooltool.py
    options:
      region: usw1

  TooltoolUsw2:
    region: us-west-2
    template: tooltool.py
    options:
      region: usw2

  TooltoolUse1:
    region: us-east-1
    template: tooltool.py
    options:
      region: use1

  # IAM Roles (global, but cloudformation needs a region)
 
  IAMRelengAPI:
    region: us-east-1
    template: iam_relengapi.py
    options:
      prod: true
        
  IAMRelengAPIStaging:
    region: us-east-1
    template: iam_relengapi.py
    options:
      prod: false
        
# vim: set ts=2 sw=2:
