# Macros that can be included below; see yaml_includes.py.  Be careful in applying these:
# the include processor doesn't automatically flatten lists or anything like that.
includes:

    # ping is allowed from anywhere in just about every SG
    global-ping:
        proto: icmp
        ports: [-1]
        hosts:
          - 0.0.0.0/0

    # most outgoing flows are completely open
    global-any:
        proto: -1
        hosts:
          - 0.0.0.0/0

    # administrative hosts have unrestricted access on all ports
    admin-access:
        proto: -1
        hosts:
          - 10.22.75.6/31  # admin1a/b
          - admin1.private.scl3.mozilla.com
          - openvpn1.corpdmz.scl3.mozilla.com
          - openvpn1.stage.corpdmz.scl3.mozilla.com
          - ssh1.corpdmz.scl3.mozilla.com
          - ssh1.stage.corpdmz.scl3.mozilla.com
          - nagios1.private.releng.scl3.mozilla.com  # note: includes tcp/5666
          - vportal1a.ops.scl3.mozilla.com
          - 10.22.240.0/20  # scl3-vpn-net
          - 10.22.20.0/25  # admin1.scl3-vpn

    # observium has universal SNMP access
    observium:
        proto: udp
        ports: [161]
        hosts:
          - observium2.private.scl3.mozilla.com

    # infra puppetizes hosts by SSHing to them from the master
    infra-puppetize:
        proto: tcp
        ports: [22]
        hosts:
          - puppet1.private.scl3.mozilla.com

    # all slave VLANs look the same
    slave-vlan-inbound:
        - proto: tcp
          ports: [22]
          hosts:
            - cruncher.build.mozilla.org
            - {include: slaveapi-servers}
            - aws-manager1.srv.releng.scl3.mozilla.com
            - aws-manager2.srv.releng.scl3.mozilla.com
        - include: admin-access
        - include: observium
        - include: infra-puppetize
        - include: global-ping

    slave-vlan-outbound:
        - include: global-any

    # host set aliases:
    slaveapi-servers: 10.26.48.16/31

    # network aliases:
    build-scl3: 10.26.52.0/22
    test-scl3: 10.26.56.0/22
    try-scl3: 10.26.64.0/22
    winbuild-scl3: 10.26.36.0/22
    wintest-scl3: 10.26.40.0/22
    wintry-scl3: 10.26.44.0/22
    pods-scl3: 10.26.128.0/17
    build-usw2: 10.132.52.0/22
    test-usw2: 10.132.56.0/22
    test2-usw2: 10.132.156.0/22
    test3-usw2: 10.132.40.0/21
    try-usw2: 10.132.64.0/22
    build-use1: 10.134.52.0/22
    test-use1: 10.134.56.0/22
    test2-use1: 10.134.156.0/22
    test3-use1: 10.134.40.0/21
    try-use1: 10.134.64.0/22
    slave-vlans:
      - {include: build-scl3}
      - {include: test-scl3}
      - {include: try-scl3}
      - {include: winbuild-scl3}
      - {include: wintest-scl3}
      - {include: wintry-scl3}
      - {include: pods-scl3}
      - {include: build-usw2}
      - {include: test-usw2}
      - {include: test2-usw2}
      - {include: test3-usw2}
      - {include: try-usw2}
      - {include: build-use1}
      - {include: test-use1}
      - {include: test2-use1}
      - {include: test3-use1}
      - {include: try-use1}

    # and port aliases
    buildbot-http-portrange: 8000-8999
    buildbot-rpc-portrange: 9000-9999

    aws-manager-ssh:
      proto: tcp
      ports: [22]
      hosts:
        - aws-manager1.srv.releng.scl3.mozilla.com
        - aws-manager2.srv.releng.scl3.mozilla.com

tests:
    description: security group for test slaves
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    apply-to:
        instances:
            tags:
                - [moz-type, tst-linux*]
                - [Name, tst-linux*-ec2-*]
        interfaces:
            tags:
                - [moz-type, tst-linux*]
    inbound:
        include: slave-vlan-inbound
    outbound:
        include: slave-vlan-outbound

build:
    description: security group for build slaves
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    apply-to:
        instances:
            tags:
                - [moz-type, bld-linux64]
                - [Name, bld-linux64-ec2-*]
        interfaces:
            tags:
                - [moz-type, bld-linux64]
    inbound:
        include: slave-vlan-inbound
    outbound:
        include: slave-vlan-outbound

try:
    description: security group for try build slaves
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    apply-to:
        instances:
            tags:
                - [moz-type, try-linux64]
                - [Name, try-linux64-ec2-*]
        interfaces:
            tags:
                - [moz-type, try-linux64]
    inbound:
        include: slave-vlan-inbound
    outbound:
        include: slave-vlan-outbound

buildbot-master:
    description: security group for buildbot masters
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        # traffic from other masters
        - proto: tcp
          ports:
            - 22  # ssh
            - {include: buildbot-rpc-portrange}
            - {include: buildbot-http-portrange}
          hosts:
            - 10.26.68.0/24  # bb.releng.scl3
            - 10.132.68.0/24  # bb.releng.usw2
            - 10.134.68.0/24  # bb.releng.use1

        # traffic from buildslaves
        - proto: tcp
          ports:
            - {include: buildbot-rpc-portrange}
          hosts: {include: slave-vlans}

        # buildbot-http from aws-managers and slaveapi
        - proto: tcp
          ports:
            - {include: buildbot-http-portrange}
          hosts:
            - {include: slaveapi-servers}
            - aws-manager1.srv.releng.scl3.mozilla.com
            - aws-manager2.srv.releng.scl3.mozilla.com

        # generic stuff
        - include: aws-manager-ssh
        - include: admin-access
        - include: observium
        - include: infra-puppetize
        - include: global-ping
    outbound:
        - include: global-any

puppet-master:
    description: security group for puppet masters
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        - proto: tcp
          ports: [443, 80, 8140]
          hosts:
            - 10.26.0.0/16
            - 10.130.0.0/16
            - 10.132.0.0/16
            - 10.134.0.0/16

        # SSH from other masters
        - proto: tcp
          ports: [22]
          hosts:
            - releng-puppet1.srv.releng.scl3.mozilla.com
            - releng-puppet2.srv.releng.scl3.mozilla.com
            # it'd be nice to be able to reference this SG here, instead
            - releng-puppet1.srv.releng.use1.mozilla.com
            - releng-puppet1.srv.releng.usw2.mozilla.com

        # generic stuff
        - include: aws-manager-ssh
        - include: admin-access
        - include: observium
        - include: infra-puppetize
        - include: global-ping
    outbound:
        - include: global-any

blobber:
    description: security group for blobber service
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        - proto: tcp
          ports: [443]
          hosts: {include: slave-vlans}
        - include: admin-access
        - include: observium
        - include: infra-puppetize
        - include: global-ping
    outbound:
        - include: global-any

nagios:
    description: security group for nagios servers
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        - include: admin-access
        - include: observium
        - include: infra-puppetize
        - include: global-ping
    outbound:
        - include: global-any

# proxxy is configured per-region; these two stanzas should be kept parallel
proxxy-vpc-use1:
    description: security group for proxxy servers in use1
    regions:
        us-east-1: vpc-b42100df
    inbound:
        - proto: tcp
          ports: [80]
          hosts:
            - {include: build-use1}
            - {include: test-use1}
            - {include: test2-use1}
            - {include: test3-use1}
            - {include: try-use1}
        - include: aws-manager-ssh
        - include: admin-access
        - include: observium
        - include: global-ping
    outbound:
        - include: global-any

proxxy-vpc-usw2:
    description: security group for proxxy servers in usw2
    regions:
        us-west-2: vpc-cd63f2a4
    inbound:
        - proto: tcp
          ports: [80]
          hosts:
            - {include: build-usw2}
            - {include: test-usw2}
            - {include: test2-usw2}
            - {include: test3-usw2}
            - {include: try-usw2}
        - include: aws-manager-ssh
        - include: admin-access
        - include: observium
        - include: global-ping
    outbound:
        - include: global-any

LogAggregators:
    description: Group for log aggregators and their load balancer
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        - proto: tcp
          ports: [1514]
          hosts:
            - 10.26.0.0/16
            - 10.130.0.0/16
            - 10.132.0.0/16
            - 10.134.0.0/16
        - include: aws-manager-ssh
        - include: admin-access
        - include: observium
        - include: global-ping
    outbound:
        - include: global-any

VCSSync:
    description: Group hg/git vcssync servers
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        - include: aws-manager-ssh
        - include: admin-access
        - include: observium
        - include: global-ping
    outbound:
        - include: global-any

signing-worker:
    description: security group for signing workers
    regions:
        us-west-1: vpc-7a7dd613
        us-west-2: vpc-cd63f2a4
        us-east-1: vpc-b42100df
    inbound:
        - proto: tcp
          ports:
            - 22  # ssh
          hosts:
          - 10.22.240.0/20  # scl3-vpn-net
        - include: admin-access
        - include: observium
        - include: infra-puppetize
        - include: global-ping
        - include: aws-manager-ssh
    outbound:
        - include: global-any
